### ISSUE TITLE
Support npm install with npat=true

### ISSUE THREAD

**Issue by ariya** [jquery/esprima#1199]
Right now, running `npm install --npat esprima` will result in the following error:

```
> node test/run.js && npm run lint && npm run coverage

runner: module.js:338
    throw err;
          ^
Error: Cannot find module 'json-diff'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
(and so on...)

**Comment by ariya** [comment]
I think the problem is because npm doesn't install the devDependencies, hence some packages needed to run the tests are not available. Thus, the proper command to test will be
```
npm install --npat --dev esprima
```

However, in that case, all the dependencies (check with `npm ls`), everything from jscs and coveralls, will run with `--npat` as well and everything fails miserably. In other words, it requires participation from all the packages involved.

Consider this circumstance, I would propose that we don't bother trying to support npat install.
