### ISSUE TITLE
`let` not allowed as a bound identifier in for-in and for-of loops

### ISSUE THREAD

**Issue by TimothyGu** [jquery/esprima#1334]
```js
> require('esprima').parse('var func = let => 0')
Error: Line 1: Unexpected token let
    at constructError (esprima.js:2388:21)
    at createError (esprima.js:2407:17)
    at unexpectedTokenError (esprima.js:2481:13)
    at throwUnexpectedToken (esprima.js:2486:15)
    at parsePrimaryExpression (esprima.js:3255:13)
    at inheritCoverGrammar (esprima.js:2662:18)
    at parseLeftHandSideExpressionAllowCall (esprima.js:3387:20)
    at inheritCoverGrammar (esprima.js:2662:18)
    at parsePostfixExpression (esprima.js:3463:16)
    at parseUnaryExpression (esprima.js:3523:20)
```

As far as I can tell, `let` is a valid Identifier and BindingIdentifier under non-strict mode, and therefore it should be allowed as a parameter.

----

ES2015 [14.2](http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions):

> ```
ArrowFunction[In, Yield] :
    ArrowParameters[?Yield] [no LineTerminator here] => ConciseBody[?In]
ArrowParameters[Yield] :
    BindingIdentifier[?Yield]
    CoverParenthesizedExpressionAndArrowParameterList[?Yield]
```

ES2015 [12.2](http://www.ecma-international.org/ecma-262/6.0/#sec-primary-expression):

> ```
CoverParenthesizedExpressionAndArrowParameterList[Yield] :
    ( Expression[In, ?Yield] )
    ( )
    ( ... BindingIdentifier[?Yield] )
    ( Expression[In, ?Yield] , ... BindingIdentifier[?Yield] )
```

ES2015 [12.1](http://www.ecma-international.org/ecma-262/6.0/#sec-identifiers):

> ```
BindingIdentifier[Yield] :
    Identifier
    [~Yield] yield
>
Identifier :
    IdentifierName but not ReservedWord
```

ES2015 [12.1.1](http://www.ecma-international.org/ecma-262/6.0/#sec-identifiers-static-semantics-early-errors)

> ```
BindingIdentifier : Identifier
   * It is a Syntax Error if the code matched by this production is contained in strict mode code and the StringValue of Identifier is "arguments" or "eval".
> 
Identifier : IdentifierName but not ReservedWord
    * It is a Syntax Error if this phrase is contained in strict mode code and the StringValue of IdentifierName is: "implements", "interface", "let", "package", "private", "protected", "public", "static", or "yield".
    * It is a Syntax Error if StringValue of IdentifierName is the same String value as the StringValue of any ReservedWord except for yield.
```

**Comment by ariya** [comment]
Can you try it again with the master branch? I believe this should covered when we tackled #1289.

**Comment by TimothyGu** [comment]
Seems like that was fixed, but the following two cases are not:

```js
for (let in a) {}
for (let of a) {}
```

**Comment by michaelficarra** [comment]
@TimothyGu The first is a valid Script, the second is not.

**Comment by TimothyGu** [comment]
Ah okay. Didn't see "[lookahead ≠ let ]" in the spec.
