### ISSUE TITLE
syntax error in esprima.js?

### ISSUE THREAD

**Issue by loldrup** [jquery/esprima#1451]
How come I get this error:

jon@Lemur:~/frontend$ browserify -t deamdify js/test_browserify.js -o js/test_bundle.js
/home/jon/frontend/node_modules/esprima/esprima.js:3734
            throw e;
            ^

Error: Line 47: Unexpected token =>
    at throwError (/home/jon/frontend/node_modules/esprima/esprima.js:1846:21)
    at throwUnexpected (/home/jon/frontend/node_modules/esprima/esprima.js:1904:9)
    at consumeSemicolon (/home/jon/frontend/node_modules/esprima/esprima.js:1983:13)
    at parseStatement (/home/jon/frontend/node_modules/esprima/esprima.js:3281:9)
    at parseSourceElement (/home/jon/frontend/node_modules/esprima/esprima.js:3505:20)
    at parseFunctionSourceElements (/home/jon/frontend/node_modules/esprima/esprima.js:3334:29)
    at parseFunctionExpression (/home/jon/frontend/node_modules/esprima/esprima.js:3477:16)
    at parsePrimaryExpression (/home/jon/frontend/node_modules/esprima/esprima.js:2194:24)
    at parseLeftHandSideExpressionAllowCall (/home/jon/frontend/node_modules/esprima/esprima.js:2293:61)
    at parsePostfixExpression (/home/jon/frontend/node_modules/esprima/esprima.js:2341:16)

**Comment by loldrup** [comment]
This is the content of js/test_browserify.js. Only 'SuperQuadric' is an AMD module : 

"use strict";

var qunit = require('qunitjs');
var three = require('three.js');  // remove
var gl_matrix_common = require('gl-matrix-common');  // remove
var gl_matrix_mat3   = require('gl-matrix-mat3');  // remove
var regression_js = require('regression.js');  // remove
var SuperQuadric = require('./cons/designs/SuperQuadric');  // remove

console.log("qunit: ", qunit);
console.log("three: ", three);
console.log("gl_matrix_common: ", gl_matrix_common);
console.log("gl_matrix_mat3: ", gl_matrix_mat3);
console.log("regression-js: ", regression_js);
console.log("SuperQuadric: ", SuperQuadric);

**Comment by ariya** [comment]
> Error: Line 47: Unexpected token =>

Can you find out the content of this Line 47?

It could be also the problem with [deamdify](https://www.npmjs.com/package/deamdify).

**Comment by loldrup** [comment]
I now think this line 47 pointer points to my file './cons/designs/SuperQuadric'. At this line, I define an 'arrow' function, which is part of ES6. I only need my project to work in Firefox, so that is OK. I don't need Babel or similar.
But how do I make esprima (or deamdify) accept ES6 syntax?

**Comment by ariya** [comment]
deamdify needs to use Esprima that supports arrow function. Can you check the Esprima version? Open `/home/jon/frontend/node_modules/esprima/esprima.js` and search for `version`.

**Comment by loldrup** [comment]
I found this:

    // Sync with *.json manifests.
    exports.version = '1.2.5';

**Comment by loldrup** [comment]
I 'transferred' this issue to the deAMDify github account:
https://github.com/jaredhanson/deamdify/issues/36#issuecomment-171083004
