### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by bykoff** [jquery/esprima#1718]
Hi! 
Everything perfect works, but today I have an error. I do nothing. Error dump bellow, please help me if you can or give me some advise how I can fix this. 
P.S.: MyStuff = path of my local folders.

```
MyStuff/node_modules/esprima/dist/esprima.js:3378
	        var error = new Error(msg);
                     ^
Error: Line 9: MyStuff/node_modules/esprima/dist/esprima.js:3378
	        var error = new Error(msg);
                     ^
Error: Line 9: Unexpected token .
    at ErrorHandler.constructError (MyStuff/node_modules/esprima/dist/esprima.js:3378:22)
    at ErrorHandler.createError (MyStuff/node_modules/esprima/dist/esprima.js:3396:27)
    at Parser.unexpectedTokenError (MyStuff/node_modules/esprima/dist/esprima.js:542:39)
    at Parser.throwUnexpectedToken (MyStuff/node_modules/esprima/dist/esprima.js:552:21)
    at Parser.consumeSemicolon (MyStuff/node_modules/esprima/dist/esprima.js:845:23)
    at Parser.parseVariableStatement (MyStuff/node_modules/esprima/dist/esprima.js:2068:15)
    at Parser.parseStatement (MyStuff/node_modules/esprima/dist/esprima.js:2552:43)
    at Parser.parseStatementListItem (MyStuff/node_modules/esprima/dist/esprima.js:1818:39)
    at Parser.parseFunctionSourceElements (MyStuff/node_modules/esprima/dist/esprima.js:2587:29)
    at Parser.parseFunctionExpression (MyStuff/node_modules/esprima/dist/esprima.js:2776:26)
    at Parser.parsePrimaryExpression (MyStuff/node_modules/esprima/dist/esprima.js:931:38)
    at Parser.inheritCoverGrammar (MyStuff/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseLeftHandSideExpressionAllowCall (MyStuff/node_modules/esprima/dist/esprima.js:1388:26)
    at Parser.inheritCoverGrammar (MyStuff/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseUpdateExpression (MyStuff/node_modules/esprima/dist/esprima.js:1482:26)
    at Parser.parseUnaryExpression (MyStuff/node_modules/esprima/dist/esprima.js:1517:26) token .
    at ErrorHandler.constructError (MyStuff/node_modules/esprima/dist/esprima.js:3378:22)
    at ErrorHandler.createError (MyStuff/node_modules/esprima/dist/esprima.js:3396:27)
    at Parser.unexpectedTokenError (MyStuff/node_modules/esprima/dist/esprima.js:542:39)
    at Parser.throwUnexpectedToken (MyStuff/node_modules/esprima/dist/esprima.js:552:21)
    at Parser.consumeSemicolon (MyStuff/node_modules/esprima/dist/esprima.js:845:23)
    at Parser.parseVariableStatement (MyStuff/node_modules/esprima/dist/esprima.js:2068:15)
    at Parser.parseStatement (MyStuff/node_modules/esprima/dist/esprima.js:2552:43)
    at Parser.parseStatementListItem (MyStuff/node_modules/esprima/dist/esprima.js:1818:39)
    at Parser.parseFunctionSourceElements (MyStuff/node_modules/esprima/dist/esprima.js:2587:29)
    at Parser.parseFunctionExpression (MyStuff/node_modules/esprima/dist/esprima.js:2776:26)
    at Parser.parsePrimaryExpression (MyStuff/node_modules/esprima/dist/esprima.js:931:38)
    at Parser.inheritCoverGrammar (MyStuff/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseLeftHandSideExpressionAllowCall (MyStuff/node_modules/esprima/dist/esprima.js:1388:26)
    at Parser.inheritCoverGrammar (MyStuff/node_modules/esprima/dist/esprima.js:833:37)
    at Parser.parseUpdateExpression (MyStuff/node_modules/esprima/dist/esprima.js:1482:26)
    at Parser.parseUnaryExpression (MyStuff/node_modules/esprima/dist/esprima.js:1517:26)
```

**Comment by ariya** [comment]
Your input has a problem. What do you parse with Esprima?

**Comment by bykoff** [comment]
Thanks for answer!
I use this gulp plugins:
gulp-uglyfly, gulp-concat, gulp-javascript-obfuscator. And for input some JS. Output result ugly inline JS. But it is very strange, because yesterday everything worked good and today I got this problem. Maybe it is important: I added regular expression in input JS today, and then I got an error, then turn back, but error still occurs.

**Comment by ariya** [comment]
Do you have an exact string that goes into Esprima? Or perhaps a simple repository that can be used to reproduce the issue? Otherwise, it is pretty to hard to infer anything at all.

**Comment by bykoff** [comment]
Hello! 
I rebuilt all at the different folder with all packages (all dependencies) and ran task again. And got a new error, it is in plugin "uglyfly-js". I suppose problem is in input JS file. But I don't understand why it worked before. Anyway it is not a problem of "esprima"!
Thank you for your attention and time!
