### ISSUE TITLE
Numeric literals in JSX fail to parse

### ISSUE THREAD

**Issue by pfhayes** [jquery/esprima#1786]
Getting "Unexpected token: ILLEGAL" errors on valid JSX

### Steps to reproduce
```js
esprima.parse('<div>{0}</div>;', {jsx: true});
```

### Expected output
A valid program

### Actual output
```
Error: Line 1: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/node_modules/esprima/dist/esprima.js:3414:27)
    at ErrorHandler.throwError (/node_modules/esprima/dist/esprima.js:3422:21)
    at Scanner.throwUnexpectedToken (/node_modules/esprima/dist/esprima.js:3505:28)
    at JSXParser.lexJSX (/node_modules/esprima/dist/esprima.js:5545:23)
    at JSXParser.peekJSXToken (/node_modules/esprima/dist/esprima.js:5603:26)
    at JSXParser.matchJSX (/node_modules/esprima/dist/esprima.js:5619:26)
    at JSXParser.parseJSXExpressionContainer (/node_modules/esprima/dist/esprima.js:5758:19)
    at JSXParser.parseJSXChildren (/node_modules/esprima/dist/esprima.js:5780:39)
    at JSXParser.parseComplexJSXElement (/node_modules/esprima/dist/esprima.js:5792:52)
```

### Relevant references
A string literal works as expected.

```js
esprima.parse('<div>{0}</div>;', {jsx: true});  // succeeds
```

**Comment by ariya** [comment]
Thanks @pfhayes for this report! I'll take a look at this.
