### ISSUE TITLE
tokeniser fails when string literal contains new line (\n)

### ISSUE THREAD

**Issue by tamslinn** [jquery/esprima#1787]
When parsing javascript with a string literal containing a line break, the tokenizer throws an error.

### Steps to reproduce

```js
esprima.tokenize('myVar = "line1\nline2"')
```

### Expected output
```js
[ { type: 'Identifier', value: 'myVar' },
  { type: 'Punctuator', value: '=' },
  { type: 'String', value: '"line1\nline2"' } ]
```

### Actual output
Error: Line 1: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/home/tamsin/node_modules/esprima/dist/esprima.js:3396:22)
    at ErrorHandler.createError (/home/tamsin/node_modules/esprima/dist/esprima.js:3414:27)
    at ErrorHandler.throwError (/home/tamsin/node_modules/esprima/dist/esprima.js:3422:21)
    at Scanner.throwUnexpectedToken (/home/tamsin/node_modules/esprima/dist/esprima.js:3505:28)
    at Scanner.scanStringLiteral (/home/tamsin/node_modules/esprima/dist/esprima.js:4292:19)
    at Scanner.lex (/home/tamsin/node_modules/esprima/dist/esprima.js:4604:26)
    at Tokenizer.getNextToken (/home/tamsin/node_modules/esprima/dist/esprima.js:6366:43)
    at Object.tokenize (/home/tamsin/node_modules/esprima/dist/esprima.js:136:36)
    at repl:1:9
   at REPLServer.defaultEval (repl.js:252:27)

Let me know if I am missing something, or if you need more information. Thanks!

**Comment by mikesherov** [comment]
Thanks for contributing. Please see the attached screenshot from the Chrome console:

![image](https://cloud.githubusercontent.com/assets/364532/24248315/2fa345f4-0fa5-11e7-9311-cb2e35354217.png)

If what you were attempting was having esprima parse:
```
myVar = "line1\nline2"
```
 you need to do `esprima.tokenize('myVar = "line1\\nline2"');`, which escapes the newline. Notice the extra `\`;

Instead, doing this: ``esprima.tokenize('myVar = "line1\\nline2"');` is like having esprima parse:
```
myVar = "line1
line2"
```
which indeed is not valid javascript.

**Comment by tamslinn** [comment]
Thanks for the answer. I don't really understand - isn't using \n a way of putting a linebreak in a string literal without breaking javascript? Using alert as a simple example: 

I don't get  an error in my JS code if I have the line
```alert('line1\nline2')```

When run I see an alert with a linebreak.

If I do this
```alert('line1\\nline2')```

The alert has \n in the middle of it, which I don't want. 

Thanks again for your help on this.

**Comment by mikesherov** [comment]
`alert('line1\\nline2')` is *actual* code. `Esprima.parse("alert('line1\\nline2')")` is Esprima parsing the *string* as if it were *actual code*!
