### ISSUE TITLE
Esprima cannot parse class method named `async get()`

### ISSUE THREAD

**Issue by rilut** [jquery/esprima#1875]
### Steps to reproduce

It fails when `async` keyword meets `get` keyword:
```js
esprima.parseScript(`class UserRepo{
    async get(id) {
        return id;
    }
}`)
```

But these are okay:

(`async`, not named `get`)

```js
esprima.parseScript(`class UserRepo{
    async notget(id) {
        return id;
    }
}`)
```

(not `async`, named `get`)

```js
esprima.parse(`(class UserRepo{
    get(id) {
        return id;
    }
})`)
```

### Expected output

```js
Script {
  type: 'Program',
  body:
   [ ClassDeclaration {
       type: 'ClassDeclaration',
       id: [Object],
       superClass: null,
       body: [Object] } ],
  sourceType: 'script' }
```

### Actual output
```
Error: Line 2: Unexpected identifier
    at ErrorHandler.constructError (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:5020:27)
    at Parser.unexpectedTokenError (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.tolerateUnexpectedToken (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:1998:42)
    at Parser.parseClassElement (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:4587:35)
    at Parser.parseClassElementList (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:4658:33)
    at Parser.parseClassBody (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:4666:33)
    at Parser.parseClassExpression (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:4695:31)
    at Parser.parsePrimaryExpression (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:2380:38)
    at Parser.inheritCoverGrammar (/Users/rilut/myproject/node_modules/esprima/dist/esprima.js:2278:37)
```

**Comment by crazyhuggins** [comment]
@rilut A quick look at all the reported issues and lack of responses from the mainainers during the last months -  I think Esprima is stall now so most likely, this will not be fixed., Maybe try to use Acorn, Cherow or ShiftJS? I moved all my projects long time ago.

**Comment by mikesherov** [comment]
Thanks for the report! Esprima doesn’t yet support async/await.

**Comment by crazyhuggins** [comment]
@rilut Esprima 4.0 supports async/await. Not sure why @mikesherov wrote that, but you find it in the [changelog](https://github.com/jquery/esprima/blob/master/ChangeLog). The two first bullet points.

**Comment by mikesherov** [comment]
@crazyhuggins is right.

**Comment by icefapper** [comment]
@mikesherov @michaelficarra Using [Jazzle](https://github.com/JazzleWare/jazzle-parser), I had come across (and reported!) this error about a year ago -- https://github.com/jquery/esprima/issues/1699
