### ISSUE TITLE
Unexpected token on export default { }

### ISSUE THREAD

**Issue by xeroxstar** [jquery/esprima#2018]
I am not sure but why i get an error when `export default` is used in the script:

```
const esprima        = require('esprima');
console.log(esprima.parse("export default {}"));
```
ERROR:

```
(node:23012) UnhandledPromiseRejectionWarning: Error: Line 1: Unexpected token
    at ErrorHandler.constructError (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:5028:27)
    at Parser.unexpectedTokenError (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:1985:39)
    at Parser.tolerateUnexpectedToken (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:1998:42)
    at Parser.parseStatementListItem (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:3365:31)
    at Parser.parseScript (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:4723:29)
    at Object.parse (C:\Users\user\Desktop\project\node_modules\esprima\dist\esprima.js:122:61)
```

Is there a way to fix it?

**Comment by xeroxstar** [comment]
I guess we need to do a small hack, i found the solution [here ](https://www.gitmemory.com/issue/jquery/esprima/1893/480594378), seems it's working:

```
const esprima    = require('esprima');
esprima["parse"] = function( input, config, delegate ) {
                var ES5Module = Boolean(input.match(/(module\.)*exports\s*\=/));
                if ( !ES5Module ) {
                    try {
                        var parsedResult = esprima.parseScript( input, config, delegate );
                        return parsedResult;
                    } catch(err) {}
                }
                return esprima.parseModule( input, config, delegate );
};
console.log(esprima.parse("export default {}"));
```
